# Generated by Django 3.2.6 on 2021-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auta',
            fields=[
                ('nr_rejestracyjny', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('marka', models.CharField(max_length=64)),
                ('rok_produkcji', models.IntegerField()),
                ('pesel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'auta',
            },
        ),
        migrations.CreateModel(
            name='Osoby',
            fields=[
                ('pesel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('typ_miejscowosci', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'osoby',
            },
        ),
        migrations.CreateModel(
            name='Wypadki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wypadekid', models.IntegerField(db_column='wypadekID')),
                ('data_wypadku', models.DateField()),
                ('nr_rejestracyjny', models.CharField(max_length=7)),
                ('wartosc_straty', models.IntegerField()),
            ],
            options={
                'db_table': 'wypadki',
            },
        ),
    ]
