# Generated by Django 3.2.6 on 2021-08-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auta',
            new_name='auto',
        ),
        migrations.RenameModel(
            old_name='Osoby',
            new_name='osoba',
        ),
        migrations.RenameModel(
            old_name='Wypadki',
            new_name='wypadek',
        ),
    ]
