# Generated by Django 3.2.4 on 2021-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0002_auto_20210822_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wypadek',
            name='id',
        ),
        migrations.AlterField(
            model_name='wypadek',
            name='wypadekid',
            field=models.IntegerField(db_column='wypadekID', primary_key=True, serialize=False),
        ),
    ]
