# Generated by Django 3.2.4 on 2021-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0003_auto_20210823_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='rok_produkcji',
            field=models.CharField(max_length=7),
        ),
    ]
