# Generated by Django 3.2.6 on 2021-08-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0004_alter_auto_rok_produkcji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='rok_produkcji',
            field=models.IntegerField(),
        ),
    ]
